name: Daily Blog Pipeline

on:
  schedule:
    - cron: "0 3 * * *"   # runs daily at 03:00 UTC
  workflow_dispatch:      # allows manual trigger

jobs:
  run-pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run pipeline
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
        run: python main.py
      - name: Upload generated blogs
        uses: actions/upload-artifact@v3
        with:
          name: blogs
          path: generated_blogs/
